Models/User.cs
#pragma warning disable CS8618
namespace WeddingPlanner.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class User
{
  [Key]
  public int UserId { get; set; }

  [Required(ErrorMessage = "Is Required.")]
  [MinLength(2, ErrorMessage = "Must be at least 2 characters.")]
  [Display(Name = "First Name")]
  public string FirstName { get; set; }

  [Required(ErrorMessage = "Is Required.")]
  [MinLength(2, ErrorMessage = "Must be at least 2 characters.")]
  [Display(Name = "Last Name")]
  public string LastName { get; set; }

  [Required(ErrorMessage = "Is Required.")]
  [EmailAddress]
  public string Email { get; set; }

  [Required(ErrorMessage = "Is Required.")]
  [MinLength(8, ErrorMessage = "Must be at least 8 characters long.")]
  [DataType(DataType.Password)]
  public string Password { get; set; }

  [NotMapped]
  [Compare("Password", ErrorMessage = "Password do not match! Please check your input.")]
  [DataType(DataType.Password)]
  [Display(Name = "Confirm Password")]
  public string ConfirmPassword { get; set; }

  public DateTime createdAt { get; set; } = DateTime.Now;
  public DateTime updatedAt { get; set; } = DateTime.Now;

  public int WeddingId { get; set; }

  public List<Wedding> Weddings { get; set; } = new List<Wedding>();
  //Many to Many -- One User can like many posts

  public List<Association> JoinedWeddings { get; set; } = new List<Association>();
}

Controllers/UserController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace WeddingPlanner.Controllers;

public class UserController : Controller
{
  private WeddingPlannerContext _context;

  public UserController(WeddingPlannerContext context)
  {
    _context = context;
  }

  private int? UserId
  {
    get
    {
      return HttpContext.Session.GetInt32("UserId");
    }
  }

  private bool loggedIn
  {
    get
    {
      return UserId != null;
    }
  }

  [HttpGet("")]
  public IActionResult LoginAndRegister()
  {
    return View("LoginAndRegister");
  }

  [HttpPost("register/new")]
  public IActionResult RegisterUser(User newUser)
  {
    if (ModelState.IsValid == false)
    {
      return LoginAndRegister();
    }

    if (_context.Users.Any(user => user.Email == newUser.Email))
    {
      ModelState.AddModelError("Email", "is already taken!");
      return LoginAndRegister();
    }

    PasswordHasher<User> Hasher = new PasswordHasher<User>();
    newUser.Password = Hasher.HashPassword(newUser, newUser.Password);

    _context.Users.Add(newUser);
    _context.SaveChanges();

    HttpContext.Session.SetInt32("UserId", newUser.UserId);

    return RedirectToAction("Dashboard");
  }

  [HttpPost("/login")]
  public IActionResult Login(LoginUser loginUser)
  {
    if (ModelState.IsValid == false)
    {
      ViewBag.AuthorizationError = "Your email or password is incorrect!";
      return LoginAndRegister();
    }

    User? foundUser = _context.Users.FirstOrDefault(u => u.Email == loginUser.LoginEmail);

    if (foundUser == null)
    {
      ModelState.AddModelError("Email", "and Password do not match.");
      return LoginAndRegister();
    }

    PasswordHasher<LoginUser> Hasher = new PasswordHasher<LoginUser>();
    PasswordVerificationResult comparePassword = Hasher.VerifyHashedPassword(loginUser, foundUser.Password, loginUser.LoginPassword);

    if (comparePassword == 0)
    {
      ModelState.AddModelError("Email", "and Password don't match!");
      return LoginAndRegister();
    }

    HttpContext.Session.SetInt32("UserId", foundUser.UserId);
    return RedirectToAction("Dashboard");
  }

  [HttpGet("/dashboard")]
  public IActionResult Dashboard()
  {
    if (UserId == null)
    {
      return LoginAndRegister();
    }

    List<Wedding> AllWeddings = _context.Weddings.Include(wedding => wedding.Planner).Include(wedding => wedding.Guests).Where(wedding => wedding.Date > DateTime.Now).ToList();

    return View("Dashboard", AllWeddings);
  }

  [HttpPost("/logout")]
  public IActionResult Logout()
  {
    HttpContext.Session.Clear();
    return RedirectToAction("LoginAndRegister");
  }
}

Controllers/WeddingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.EntityFrameworkCore;

namespace WeddingPlanner.Controllers;

public class WeddingController : Controller
{
  private int? UserId
  {
    get
    {
      return HttpContext.Session.GetInt32("UserId");
    }
  }

  private bool loggedIn
  {
    get
    {
      return UserId != null;
    }
  }

  private WeddingPlannerContext _context;

  public WeddingController(WeddingPlannerContext context)
  {
    _context = context;
  }

  [HttpGet("/weddings/create")]
  public IActionResult Create()
  {
    if (!loggedIn)
    {
      return RedirectToAction("LoginAndRegister", "User");
    }
    return View("CreateWedding");
  }

  [HttpPost("/weddings/new")]
  public IActionResult New(Wedding newWedding)
  {
    if (UserId == null)
    {
      return RedirectToAction("LoginAndRegister", "User");
    }

    if (ModelState.IsValid == false)
    {
      return Create();
    }

    newWedding.UserId = (int)UserId;
    _context.Weddings.Add(newWedding);
    _context.SaveChanges();

    return RedirectToAction("Dashboard", "User");
  }

  [HttpGet("/weddings/{weddingId}")]
  public IActionResult ViewOneWedding(int weddingId)
  {
    if (!loggedIn)
    {
      return RedirectToAction("LoginAndRegister", "User");
    }

    Wedding? wedding = _context.Weddings.Include(wedding => wedding.Planner).Include(wedding => wedding.Guests).ThenInclude(attendee => attendee.Attendee).FirstOrDefault(wedding => wedding.WeddingId == weddingId);

    if (wedding == null)
    {
      return RedirectToAction("Dashboard", "User");
    }
    return View("SingleWedding", wedding);
  }

  [HttpPost("/weddings/{weddingId}/attend")]
  public IActionResult JoinWedding(int weddingId)
  {
    if (UserId == null)
    {
      return RedirectToAction("LoginAndRegister", "User");
    }

    Association? existingRSVP = _context.UserWeddingSignups.FirstOrDefault(rsvp => rsvp.UserId == UserId && rsvp.WeddingId == weddingId);

    if (existingRSVP == null)
    {
      Association newRSVP = new Association()
      {
        WeddingId = weddingId,
        UserId = (int)UserId
      };

      _context.UserWeddingSignups.Add(newRSVP);
    }
    else
    {
      _context.UserWeddingSignups.Remove(existingRSVP);
    }

    _context.SaveChanges();
    return RedirectToAction("Dashboard", "User");
  }
}

Views/User/Dashboard.cshtml
@model List<Wedding>

<h2>Welcome to Wedding Planner</h2>

<table class="table">
  <thead>
    <tr>
      <th>Wedding</th>
      <th>Date</th>
      <th>Guest</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach (Wedding wedding in Model)
    {
      bool alreadyAttending = wedding.Guests.Any(guest => guest.UserId == Context.Session.GetInt32("UserId"));

      <tr>
        <td><a asp-controller="Wedding" asp-action="ViewOneWedding"
          asp-route-weddingId="@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a>
        </td>
        <td>@wedding.Date.ToString("MMMM dd yyyy")</td>
        <td>@wedding.Guests.Count</td>
        <td>
          <form asp-controller="Wedding" asp-action="JoinWedding" asp-route-weddingId="@wedding.WeddingId" method="POST">
            <button>
              @if (alreadyAttending)
              {
                <span>Unattend</span>
              }
              else
              {
                <span>RSVP</span>
              }
            </button>
          </form>
        </td>
      </tr>
    }
  </tbody>
</table>

<a class="btn btn-success" asp-controller="Wedding" asp-action="Create">New Wedding</a>

Views/User/LoginAndRegister.cshtml
@if (ViewBag.AuthorizationError != null)
{
  <p class="text-danger font-weight-bold">@ViewBag.AuthorizationError</p>
}

<partial name="_Register"></partial>
@if (Context.Session.GetInt32("UserId") == null)
{
  <partial name="_Login"></partial>
}

Views/User/_Login.cshtml
@model LoginUser

<h3>Login</h3>

<form asp-controller="User" asp-action="Login" method="POST">
  <div class="mb-3">
    <label asp-for="LoginEmail"></label>
    <span asp-validation-for="LoginEmail" class="text-danger font-weight-bold"></span>
    <input asp-for="LoginEmail" class="form-control">
  </div>
  <div class="mb-3">
    <label asp-for="LoginPassword"></label>
    <span asp-validation-for="LoginPassword" class="text-danger font-weight-bold"></span>
    <input asp-for="LoginPassword" class="form-control">
  </div>

  <button>Login</button>
</form>

Views/User/_Register.cshtml
@model User

<div class="flex-grow-0">
  <h3>Register</h3>
  <form asp-controller="User" asp-action="RegisterUser" method="POST">
    <div class="mb-3">
      <label asp-for="FirstName"></label>
      <span asp-validation-for="FirstName" class="text-danger font-weight-bold"></span>
      <input asp-for="FirstName" class="form-control">
    </div>
    <div class="mb-3">
      <label asp-for="LastName"></label>
      <span asp-validation-for="LastName" class="text-danger font-weight-bold"></span>
      <input asp-for="LastName" class="form-control">
    </div>
    <div class="mb-3">
      <label asp-for="Email"></label>
      <span asp-validation-for="Email" class="text-danger font-weight-bold"></span>
      <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
      <label asp-for="Password"></label>
      <span asp-validation-for="Password" class="text-danger font-weight-bold"></span>
      <input asp-for="Password" class="form-control">
    </div>
    <div class="mb-3">
      <label asp-for="ConfirmPassword"></label>
      <span asp-validation-for="ConfirmPassword" class="text-danger font-weight-bold"></span>
      <input asp-for="ConfirmPassword" class="form-control">
    </div>
    <button>Register</button>
  </form>
</div>